# Generated by Django 5.0 on 2025-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_investmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmodel',
            name='company',
            field=models.CharField(max_length=150),
        ),
    ]
