# Generated by Django 5.0 on 2025-03-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stock'),
        ),
    ]
