# Generated by Django 5.0 on 2025-03-21 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_newsheadlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsheadlines',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.stock'),
            preserve_default=False,
        ),
    ]
