# Generated by Django 5.0 on 2025-03-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usercompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCompany',
        ),
    ]
